version: "3.9"
name: random_prize
services:
  nginx:
    container_name: nginx
    image: nginx:1.17.8
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
    links:
      - php_fpm
  php_fpm:
    container_name: php_fpm
    build: php
    working_dir: /var/www
    volumes:
      - ../:/var/www
